### ISSUE TITLE
[macOS][Menu] Unable to scroll to the bottom of the Menu

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#147] opened 2021-02-08 22:49 UTC
## Current behavior

Unable to scroll in the menu. Multiple issues to access the items at the bottom of the menu

## Expected behavior
The menu should scroll when items are expanded

## How to reproduce it (as minimally and precisely as possible)
1. From the left menu expand all sections
2. Scroll to the bottom of the Menu
3. Notice at one point it gets stuck and cannot access the items at the bottom of the list

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment] 2021-02-09 12:16
@DennyPerez18 the title mentions UWP, but I am not able to reproduce it there. Is the issue macOS only? Thanks :-)

**Comment by dr1rrb** [comment] 2021-03-17 02:29
Should have been fixed by https://github.com/unoplatform/uno/pull/5322

**Closed by dr1rrb** 2021-03-17 02:29 UTC
Labels: kind/bug, triage/untriaged
