### ISSUE TITLE
[WASM][PersonPicture] ProfilePicture image is not displayed

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Gallery#38] opened 2020-09-25 18:55 UTC
## Current behavior

![WASM Image not displayed](https://user-images.githubusercontent.com/49959074/94305089-a769b780-ff3e-11ea-86f8-329b599ebf7f.png)

## Expected behavior

![UWP PersonPicture](https://user-images.githubusercontent.com/49959074/94305100-ad5f9880-ff3e-11ea-823c-72b848bdd418.png)

## How to reproduce it (as minimally and precisely as possible)

1. Launch app
2. Navigate to PersonPicture
3. Notice that the image for the ProfilePicture is not displayed

## Environment

Nuget Package:
Uno.UI

Package Version(s):
3.1.0-dev.447

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment] 2021-02-05 22:10
Duplicate of https://github.com/unoplatform/uno/issues/5132

**Comment by kazo0** [comment] 2021-02-05 22:11
woops not a dupe

**Closed by kazo0** 2021-02-05 22:10 UTC
Labels: kind/bug, triage/untriaged

**Comment by kazo0** [comment] 2021-02-05 22:20
Fix in latest canary
