### ISSUE TITLE
[iOS][Android][PersonPicture] Group and Single person image does not display correctly

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/Uno.Gallery#39] opened 2020-09-25 19:41 UTC
## Current behavior
iOS:
![iOS personalpicture](https://user-images.githubusercontent.com/49959074/94308982-5c9f6e00-ff45-11ea-871c-3e84be4a1881.png)

Android:
![Android personalpicture](https://user-images.githubusercontent.com/49959074/94308998-61642200-ff45-11ea-96a9-bd95581a4ba6.png)

## Expected behavior
![UWP PersonPicture - Copy](https://user-images.githubusercontent.com/49959074/94309012-67f29980-ff45-11ea-861f-ece673427fa3.png)

## How to reproduce it (as minimally and precisely as possible)

1. Launch app
2. Navigate to PersonPicture
3. Notice that the image for a single person or group is not displayed correctly

## Environment

iPhone 8 iOS 13.3
Samsung S10e Android 10

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment] 2021-02-05 22:10
Duplicate of https://github.com/unoplatform/uno/issues/5132

**Closed by kazo0** 2021-02-05 22:10 UTC
Labels: kind/bug, triage/untriaged
