### ISSUE TITLE
[WASM] Theme Switching at times fails 

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/Uno.Gallery#974] opened 2023-09-06 15:37 UTC
## Current behavior

It's hard to reproduce, and it's more prone to happen in the ShadowContainer page, but also happens in other pages.

![wasm issue 2](https://github.com/unoplatform/Uno.Gallery/assets/114886335/b5523126-7347-4a22-9ba6-9dea15855b3d)
![image](https://github.com/unoplatform/Uno.Gallery/assets/114886335/e3c7bf47-aa79-44b5-a40d-9821dd4c1255)

## How to reproduce it (as minimally and precisely as possible)

It won't fail all the time, and that causes the issue hard to reproduce.

1. Launch Gallery on Dark Theme
2. Navigate to ShadowContainer (or other page)
3. Change the theme

## Environment

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by agneszitte** [comment] 2023-09-18 19:13
Similar issue on Android -> https://github.com/unoplatform/Uno.Themes/issues/1033

**Comment by Xiaoy312** [comment] 2023-09-26 04:20
the issue only found (from report and randomly observed scenarios) in sample page's root grid:
- ShadowContainerSamplePage\Grid
  	```xml
      <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
	```
- ButtonSamplePage\Grid
  	```xml
      <Grid Background="{StaticResource ApplicationPageBackgroundThemeBrush}">
	```
    ^ they are of different resource markup: static vs theme,
    ^ yet the problem can happen from both pages
	^ it is also worth noting that, the shell also uses that same brush in its root grid, yet we don't see the same problem happening..?

the issue is hard to reproduce, since it requires a lot of theme-switching back and forth if unlucky
	^ it can happen on the 1st try, or the nth...
	^ we tried to reproduce on android, but did not succeed before giving up
the problem is also specific to the sample pages' "root grid" only, as nothing else is behaving the same

the problematic brush:
```xml
  @ Uno.Gallery\Uno.Gallery.Shared\Views\Colors.xaml
  <ResourceDictionary>
      <SolidColorBrush x:Key="ApplicationPageBackgroundThemeBrush" Color="{ThemeResource SurfaceColor}" />
```
^ in themes, we have already moved away from this kind of setup

experiment:
```xml
<ResourceDictionary>
   <ResourceDictionary.ThemeDictionaries>
        <ResourceDictionary x:Key="Light">
            <SolidColorBrush x:Key="ThemedBrush_StaticColor" Color="{StaticResource SurfaceColor}" />
        <ResourceDictionary x:Key="Dark">
            <SolidColorBrush x:Key="ThemedBrush_StaticColor" Color="{StaticResource SurfaceColor}" />
    <SolidColorBrush x:Key="ApplicationPageBackgroundThemeBrush" Color="{ThemeResource SurfaceColor}" />
    <SolidColorBrush x:Key="StaticBrush_ThemedColor" Color="{ThemeResource SurfaceColor}" />
<Grid ColumnDefinitions="*,*,*">
    <Border Grid.Column="0" Background="{ThemeResource ApplicationPageBackgroundThemeBrush}" />
    <Border Grid.Column="1" Background="{ThemeResource ThemedBrush_StaticColor}" />
    <Border Grid.Column="2" Background="{ThemeResource StaticBrush_ThemedColor}" />
```
result:
![image](https://github.com/unoplatform/Uno.Gallery/assets/2359550/9de7f2bf-5717-44b3-bf6c-9c80a70ba2db)
- only column0 with ApplicationPageBackgroundThemeBrush failed..?
- ThemedBrush_StaticColor & StaticBrush_ThemedColor are working
    and, StaticBrush_ThemedColor is the same setup as ApplicationPageBackgroundThemeBrush..?
- note: ApplicationPageBackgroundThemeBrush is also defined in fluent resource, 
    but we can confirm our ApplicationPageBackgroundThemeBrush was used (by changing its color)

**Comment by jeromelaban** [comment] 2023-09-28 15:01
May be related to https://github.com/unoplatform/uno/issues/13855

**Comment by Xiaoy312** [comment] 2023-09-28 15:26
> May be related to [unoplatform/uno#13855](https://github.com/unoplatform/uno/issues/13855)

i would say it is different. 13855 can be consistently reproduced all the time, in the other theme than started theme.
this 974 is hard to reproduce and heavily rng dependent, plus it can be seen occurs on both themes.

**Comment by Xiaoy312** [comment] 2023-09-28 15:58
I should add the reason, I wanted to focus on the painting part, is that:
```
printing Border.Brush.Color gives us the correct color, BUT VISUALLY that is not what we got...
    Border // Background=White, Visibility=Visible
    Border // Background=White, Visibility=Visible
    document.getElementById('790642').children[0].style['background-color']
        'rgb(48, 45, 55)'
    document.getElementById('790642').children[1].style['background-color']
        'rgb(255, 255, 255)'
```

**Comment by jeromelaban** [comment] 2023-09-29 03:07
@Xiaoy312 is there are previous version of uno that does not expose this behavior?

**Comment by sakshi173** [comment] 2023-11-21 03:49
I am not able to reproduce this defect, due to that closing it.

**Closed by sakshi173** 2023-11-21 03:49 UTC
Labels: kind/bug, triage/untriaged
