### ISSUE TITLE
[Gallery][Canary][Android]Blank Screen After Selecting Components in Gallery Canary

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/Uno.Gallery#1167] opened 2024-09-09 18:51 UTC
## Current behavior

When the Gallery Canary app is opened on Android, the overview page appears as expected. However, after selecting any component from the menu, the screen turns blank. The content only becomes visible after switching to landscape mode. Upon killing and reopening the app, the issue persists, and the same behavior is observed.
Version: 1.6.0 (209093234)

https://github.com/user-attachments/assets/446f3e14-56a7-4e8d-808d-1ccaea97594f

## Expected behavior

After selecting any component from the menu, the content should display immediately without requiring a switch to landscape mode. The app should function consistently, even after being reopened.
## How to reproduce it (as minimally and precisely as possible)

1. Download, install and open Gallery canary on Android device from TestCentre
2. Keep your device on portrait mode.
3. Select any component from Menu.
4. Observe the blank screen.
5. Put you phone in landscape mode and observe the text will appear now and even in portrait it will appear.
6. Close and apen the app, all the content will be visible.
7. Kill the app and select component, again the blank screen will appear.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment] 2024-09-10 23:58
This behavior started as of Uno.WinUI 5.4.0-dev.1515 which is from this PR: https://github.com/unoplatform/uno/pull/17967

@Youssef1313 Do you see anything funky with how we are navigating in Gallery that would cause a blank screen due to the that PR being merged?

**Comment by Youssef1313** [comment] 2024-09-12 08:34
The regression is coming from Uno.WinUI 5.4.0-dev.1512 which is https://github.com/unoplatform/uno/pull/17966 (we only released 1510 and 1515). This PR fixes attached DP inheritance which previously wasn't working correctly. The only DP I know of that can have impact is NameScope. I'm still investigating.

**Comment by Youssef1313** [comment] 2024-09-12 10:04
I'm unable to root it down further 😕

**Comment by Youssef1313** [comment] 2024-09-13 15:31
@jhanvi03 Are you able to check if it's Android only or if it also happens on iOS?

**Comment by jhanvi03** [comment] 2024-09-13 17:26
@Youssef1313, The issue is not reproducible on iOS.

**Comment by Xiaoy312** [comment] 2024-09-13 17:48
Are we able to confirm, whether this issue only happen with said (Theming > Cupertino) page or it is any page?
It would be worth to also test a more pages to see if the problem happens on a specific group of pages, only a single page or any page.
Don't need to test every navigation possible, but just to a few more data points.

**Comment by Youssef1313** [comment] 2024-09-13 17:49
Any navigation as far as I tested

**Closed** 2024-09-15 20:40 UTC
Labels: kind/bug, triage/untriaged, area/canary, platform/android
