### ISSUE TITLE
Add JumpList sample

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Gallery#32] opened 2020-09-24 06:45 UTC
## What would you like to be added:

Sample page for the `JumpList` API. 

## Why is this needed:

To show how to create app shortcuts on iOS, Android and Windows.

## For which Platform:

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

**Comment by morning4coffe-dev** [comment] 2023-09-16 21:34
Duplicate of #483

**Closed by morning4coffe-dev** 2023-09-16 21:34 UTC
Labels: kind/enhancement, triage/untriaged
