### ISSUE TITLE
[macOS] [Menu] Acrylic and ViewBox sections from the left menu are not aligned

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#116] opened 2021-02-05 05:15 UTC
## Current behavior
![Screen Shot 2021-02-04 at 11 52 16 PM](https://user-images.githubusercontent.com/38770890/106992046-8ebbaa80-6745-11eb-8370-05a5771ac130.png)

1. From the left menu scroll to the bottom
2. Observe the Acrylic and ViewBox under Features section
3. Notice items are not aligned 

## Expected behavior
Items should be aligned with all the items under the Features group section

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment] 2021-02-05 14:09
Not able to reproduce with latest master. May have been addressed by the addition of the MUXC NavigationView

@DennyPerez18 Can you try again with the latest code? Thanks!

**Comment by MartinZikmund** [comment] 2021-02-06 23:55
Set for QA and closed, but it is definitely fixed by the MUX NavView

**Closed** 2021-02-06 23:54 UTC
Labels: kind/bug, triage/untriaged
