### ISSUE TITLE
[Gallery][iOS] AutoSuggestBox- The indentation for all the displayed control names with definitions is incorrect.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/Uno.Gallery#1122] opened 2024-06-18 17:30 UTC
## Current behavior
![autosuggest issue 1](https://github.com/unoplatform/Uno.Gallery/assets/74563602/d586c784-35f9-430c-b17d-81149c122201)
![autosuggest issue 2](https://github.com/unoplatform/Uno.Gallery/assets/74563602/e26290ac-bf80-4769-adb0-35250b2cc930)

## Expected behavior
![Screenshot_20240618_225624_Uno Gallery](https://github.com/unoplatform/Uno.Gallery/assets/74563602/d44dc574-3ec2-4565-b28e-e273dadb5111)

## How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap "Autosuggest Box" from the "UI Components" list.
3. Type any letter in the ' Autosuggest box with searchbox experience'
4. Make sure combo box list opens with all the controls names.
5. Notice that the indentation for all the displayed control names with definitions is incorrect.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by morning4coffe-dev** [comment] 2024-06-18 20:24
Thanks @sakshi173! I can reproduce this issue even in the search AutoSuggestBox on all platforms: 
![image](https://github.com/unoplatform/Uno.Gallery/assets/78549750/7f6b5b17-8f45-4a9f-9ad8-6183b719a704)
I will have a look from where this might be coming from.

**Comment by morning4coffe-dev** [comment] 2024-06-19 15:42
I tested this with multiple versions and I am not able to replicate outside Gallery. I think it might have something to do with the default Material styling.

**Comment by agneszitte** [comment] 2024-07-03 16:17
@morning4coffe-dev we will need to sync on this issue when you have some time

**Comment by morning4coffe-dev** [comment] 2024-07-03 16:56
@agneszitte Yes. I will let you know and I will summarize the details I discovered. The issue got fixed only with the search box at the moment.

**Comment by agneszitte** [comment] 2024-09-05 00:29
@morning4coffe-dev can you explain why this issue is blocked, please?

**Comment by agneszitte** [comment] 2024-10-04 21:30
@morning4coffe-dev fyi more info on this related issue : https://github.com/unoplatform/uno/issues/15967#issuecomment-2392302848

**Comment by agneszitte** [comment] 2024-10-04 21:41
@morning4coffe-dev I am closing this issue as it is similar to https://github.com/unoplatform/Uno.Gallery/issues/1069
And mainly like @Xiaoy312 mentioned, normally the problem is the same nature as: https://github.com/unoplatform/Uno.Gallery/issues/1093 where right now we have the Material theme for the flyout instead of the Fluent theme

**Closed by agneszitte** 2024-10-04 21:41 UTC
Labels: kind/bug, triage/untriaged, area/canary, platform/ios
